# Generated by Django 2.2.2 on 2020-07-21 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='конец события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminder',
            field=models.DurationField(choices=[(datetime.timedelta(0, 3600), 'За час'), (datetime.timedelta(0, 7200), 'За 2 часа'), (datetime.timedelta(0, 14400), 'За 4 часа'), (datetime.timedelta(1), 'За день'), (datetime.timedelta(7), 'За неделю')], verbose_name='напомнить за'),
        ),
    ]
