# Generated by Django 2.2.2 on 2020-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_auto_20200721_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='need_remind',
            field=models.BooleanField(default=False, verbose_name='напомнить?'),
        ),
    ]
