# Generated by Django 2.2.2 on 2020-07-23 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshop', '0003_event_need_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='кто?'),
            preserve_default=False,
        ),
    ]
